#+title: Cryptography

This project is going to contain multiple parts. Why I first learned of these ciphers independently, the code is based on Al Sweigart's version. I updated the code to use f-strings. The first is the classic Caesar cipher. The second is a Caesar cipher hacker. And the third is the Vigenere cipher.

** Caesar Cipher

The Caesar cipher was updated to use the python `if __name__ == "__main__"` idiom. Hopefully this will help students get more comfortable with it. It also provides opportunity for students to see the similarities between the Caesar cipher and the Vigenere cipher. When refactored in this manner we can reuse the `main()` and `get_mode()` functions.

- [[file:caesar_cipher.py][caesar_cipher.py]]
- [[file:caesar_cipher_template.py][caesar_cipher_template.py]]

** Caesar Hacker

- [[file:caesar_hacker.py
][caesar_hacker.py]]

** Vigenere Cipher

- [[file:vigenere.py][vigenere.py]]
- [[file:./vigenere_template.py][vigenere_template.py]]
- [[https://firewalledreplit.com/@MrHelmstedter/vigeneretemplate#main.py][replit template]]
