#+title: Exercises
#+date: <2024-03-08 Fri>

* 100 Exercises For Practicing Python
** Beginner-level exercises
*** Exercise 1
Write a function that declares 3 variables, ~a~, ~b~, and ~c~, assigning them the values 1, "France", and 36.2 respectively. Then return all three variables.
*** Exercise 2
Write a funtion that declares a variable ~greeting~ and initialize it with the value ~'hello'~. Then modify this same variable to contain the value ~'how are you'~. Return the content of the variable after modification.
*** Exercise 3
Write a function that declares 2 variables ~x~ and ~y~. Assign them the values ~3~ and ~8.5~ respectively, then convert the type or these variables to strings. Return these variables after modification.
*** Exercise 4
Write a function that asks the user for their weight in kilograms, then stores it in a variable. Return the value entered by the user.
*** Exercise 5
Write a function that has a parameter called ~param~. Inside the function, check whether ~param~ is an integer or a string. If it's an integer, the function should return ~"Integer"~, otherwise it should return ~"String"~.
*** Exercise 6
*** Exercise 7
*** Exercise 8
*** Exercise 9
*** Exercise 10
*** Exercise 11
